default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: linechatgpt_development

test:
  <<: *default
  database: linechatgpt_test

production:
  <<: *default
  host: <%= Rails.application.credentials.database.host %>
  database: <%= Rails.application.credentials.database.database %>
  username: <%= Rails.application.credentials.database.username %>
  password: <%= Rails.application.credentials.database.password %>
